### ISSUE TITLE
Publish first v1 version

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny-action#1]
This is a tracking issue of what is needed to publish a first `v1` version. When it is published it will show up in the GitHub marketplace for everyone which is nice for discoverability.

Primarily right now need to test it on more repos to see if it behaves well, and look into performance / build times.

**Comment by repi** [comment]
Tagged a first `v0.1.0` release and `v0`, the latter will be updated as we do minor and patch updates.

Consider these pre-release versions, and are also not published on the GitHub Marketplace. But we hope to do first proper  `v1` next week

**Comment by repi** [comment]
Feel the cargo deny format and feature set has been pretty stable now, right @Jake-Shadle ? so can be time to do a v1 of the action.

**Comment by Jake-Shadle** [comment]
Yah, I think a v1 of the action would be ok for now!

**Comment by repi** [comment]
Cool, can always be more versions after that! :P 

I'll make an attempt, and then it can be published to the marketplace as well

**Comment by repi** [comment]
Boom! https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v1.0.0

**Comment by Veetaha** [comment]
Huge thanks, guys! I hope you'll keep it up-to-date because this is very lightweight and useful!
