### ISSUE TITLE
failed to deserialize config from...

### ISSUE THREAD

**Issue by Luro02** [EmbarkStudios/cargo-deny-action#13]
I tried to use this, but it is not working :/
https://github.com/sile/hls_m3u8/pull/44/checks?check_run_id=461139614

---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device:**

**Additional context**

**Comment by repi** [comment]
It wrote out in the error that your `deny.toml` config is not valid, and pointed to the specific line:

2020-02-21 21:07:44 [ERROR] failed to deserialize config from '/github/workspace/deny.toml': unknown field `yanked`, expected one of `db-path`, `db-url`, `vulnerability`, `unmaintained`, `notice`, `ignore`, `severity-threshold` for key `advisories` at line 178 column 1

check out the [cargo-deny book](https://embarkstudios.github.io/cargo-deny/index.html) on how to create a valid config

**Comment by Luro02** [comment]
okay, thanks.

I did expect the default toml to work without having to change anything, except for the specific changes, that your project needs (for example blacklisting crate x) 

Therefore I thought this was a bug 😕
