### ISSUE TITLE
Unclear error: unable to find metadata section in Cargo.lock

### ISSUE THREAD

**Issue by antifuchs** [EmbarkStudios/cargo-deny-action#16]
**Describe the bug**

Recently, my CI builds have failed with 
```
2020-05-16 15:38:32 [ERROR] unable to find metadata section in Cargo.lock
```

It sounds like this is https://github.com/EmbarkStudios/cargo-deny/issues/56, but as far as I can tell, this has been resolved & a release published months ago (plus, the same code did run the action correctly before).

**To Reproduce**

* cargo deny config: https://github.com/antifuchs/governor/blob/6eec6f36058faedc5b0be3228d65f7eb8191906d/deny.toml
* github ci setup: https://github.com/antifuchs/governor/blob/6eec6f36058faedc5b0be3228d65f7eb8191906d/.github/workflows/cargo_deny.yml

**Expected behavior**
I would expect cargo deny to correctly parse my Cargo configuration and probably tell me some crate configs are wrong.

**CI runs**

Here's a failed run: https://github.com/antifuchs/governor/runs/681094137

**Additional context / attempt at diagnosis**

It looks like this is trying to use the 0.4.2 version of cargo deny: https://github.com/antifuchs/governor/runs/681094137#step:2:30 - but [the Dockerfile pulls in 0.6.7](https://github.com/EmbarkStudios/cargo-deny-action/blob/master/Dockerfile#L5)! Is something wrong with the way the github action is configured, or is github itself having a hiccup there?

**Comment by antifuchs** [comment]
Oooooh oh no. I just saw that I'm configuring it as `@v0` instead of a more recent release. Ooops.

**Comment by repi** [comment]
We recently did release `@v1` so was just about to suggest to try that out and see if this reproduces on it!

**Comment by antifuchs** [comment]
This totally fixes things - thanks for the quick follow-up! Also worth noting that dependabot has (alpha) support for github actions, which I've now enabled for this repo (-:

**Comment by repi** [comment]
Awesome!
