### ISSUE TITLE
Failing to load advisory database

### ISSUE THREAD

**Issue by djc** [EmbarkStudios/cargo-deny-action#23]
**Describe the bug**

https://github.com/djc/corda-rpc/actions/runs/283774748

2020-10-02 06:50:00 [ERROR] failed to load advisory database: parse error: unexpected character found: ``` at line 1 column 1

**Comment by djc** [comment]
This looks like it happened because it was still using cargo-deny-actions@v0, which presumably got stuck on an older version of cargo deny that doesn't support the latest advisory database.

**Comment by repi** [comment]
Ah too bad it broke, but yes `v0` was an unstable first release that `v1` replaced
