### ISSUE TITLE
Reduce image size with alpine as base

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny-action#3]
Wanted to use alpine as as a docker image base, but as `cargo-deny` requires Cargo to be installed (due to `cargo_metadata` crate that runs the `cargo` command) I'm simply using the Rust debian image as base now instead.

If `cargo-deny` would support linking in Cargo then it would be fully standalone and using alpine would be easy, tracked in https://github.com/EmbarkStudios/cargo-deny/issues/54

May also be able to switch to alpine and just install Cargo to it and the minimal dependencies needed

**Comment by Jake-Shadle** [comment]
In the meantime you can use the `:slim` variant of the rust image, which is based on the slim debian and shaves a few hundred MiB off.

**Comment by repi** [comment]
Good suggestion, will try!

**Comment by repi** [comment]
That reduced the image size ffrom 1.6 GB to 1.0 GB, still kinda huge but at least better

**Comment by AlexTMjugador** [comment]
Alpine is already used as a base image:

https://github.com/EmbarkStudios/cargo-deny-action/blob/f2d2f98857d524436b31aa639bac5edc10863b08/Dockerfile#L1

Therefore, I think that this issue can be closed, as it was resolved.
