### ISSUE TITLE
Latest release says it's 1.2.20 when it should say 1.2.10

### ISSUE THREAD

**Issue by lfrancke** [EmbarkStudios/cargo-deny-action#44]
A simple typo here: https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v1.2.10

It says "1.2.20" in the headline when it should say 1.2.10.

**Comment by Jake-Shadle** [comment]
Oops, thanks!

**Comment by lfrancke** [comment]
Could it also maybe be that you didn't push main? I see the tag but nothing in main

**Comment by Jake-Shadle** [comment]
Oops, thanks, again!
