### ISSUE TITLE
Add CD for docker images to be uptodate with cargo and rust 

### ISSUE THREAD

**Issue by xoac** [EmbarkStudios/cargo-deny-action#46]
**Describe the bug**

```
Error: -17 09:39:39 [ERROR] `cargo metadata` exited with an error: error: failed to parse manifest at `/github/workspace/Cargo.toml`

Caused by:
  feature `strip` is required

  The package requires the Cargo feature called `strip`, but that feature is not stabilized in this version of Cargo (1.58.0 (f01b232bc 2022-01-19)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-strip-option for more information about the status of this feature.
  ```
So basically the container use old version of cargo. This could be fixed by scheduling build new image every time new stable rust is released. [Dockerfile make sure it's up to date when building](https://github.com/EmbarkStudios/cargo-deny-action/blob/main/Dockerfile#L11)

source of error: https://github.com/xoac/signer-flow/runs/5583604418?check_suite_focus=true

**Comment by Jake-Shadle** [comment]
Closed in https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v1.2.13, you can now specify which cargo version you want to use.
