### ISSUE TITLE
The marketplace version is significantly lagging behind

### ISSUE THREAD

**Issue by V0ldek** [EmbarkStudios/cargo-deny-action#65]
The version on GitHub Action Marketplace for this action is [v1.2.1](https://github.com/marketplace/actions/cargo-deny), which lags behind the actual release (v1.5.4 right now).

![image](https://github.com/EmbarkStudios/cargo-deny-action/assets/20441980/c38f4c94-97fb-47da-ae1c-99b1048d0bc5)

**Comment by repi** [comment]
Fixed
