### ISSUE TITLE
`EmbarkStudios/cargo-deny-action@v1` fails due to `cargo metadata` - no such file or directory

### ISSUE THREAD

**Issue by Byron** [EmbarkStudios/cargo-deny-action#71]
It just happened when running CI in a PR, here is the log: https://github.com/Byron/gitoxide/actions/runs/7884315019/job/21513814089?pr=1288 .

Since I changed nothing about it and [the setup is standard](https://github.com/Byron/gitoxide/blob/68a7079de10a640b103b57b33dab8871b78d51a9/.github/workflows/ci.yml#L180-L186), I assume something changed here and just wanted you to know this is happening. 
Here is [a link to deny.toml](https://github.com/Byron/gitoxide/blob/8fd79497bf52dd8cdf3b6f2c2c6b02a60571d191/deny.toml#L1-L0) for completeness.

**Comment by torokati44** [comment]
Came here to report this, was glad to see it already done! :)

We're also getting this here: https://github.com/ruffle-rs/ruffle/actions/runs/7884522024/job/21513697259

**Comment by Byron** [comment]
What's strange is that this wasn't caught by CI here, even though it does build the docker image and runs presumably exhaustive tests.

I think a major outcome of this issue's resolution would be to update CI to catch this kind of issue in future, just because failure to do so can be so devastating.

**Comment by Jake-Shadle** [comment]
It doesn't run exhaustive tests, or at least, not the same ones as the action itself. I'll fix.

**Comment by Jake-Shadle** [comment]
@Byron can you quickly check if adding `manifest-path: ./Cargo.toml` resolves this? The default I added is theoretically the exact same as if the option isn't set but apparently that is wrong.

**Comment by ijc** [comment]
@Jake-Shadle `./Cargo.toml` helped in our case but `Cargo.toml` didn't. Which is even more puzzling...

**Comment by Jake-Shadle** [comment]
Thanks for trying that out, I have a test now that excercises it, I forgot there are working directory shenanigans inside cargo-deny so it makes sense the ./ would fix it.
