### ISSUE TITLE
Question: does it make sense to run cargo-deny on different OSes?

### ISSUE THREAD

**Issue by wiktor-k** [EmbarkStudios/cargo-deny-action#77]
Hi,

I was planning to use this action but noticed it works only on Linux (since it's a docker container) and I'm wondering if it makes any sense to run it on macOS and Windows (I had a matrix build and used cargo-deny from crates.io previously).

Or maybe cargo-deny doesn't depend on any target OS and I just should use this action on Linux and that's it?

Thanks for clarifying and, of course, for this excellent piece of software! :wave:

**Comment by Jake-Shadle** [comment]
The results are the same regardless of the host.

**Comment by wiktor-k** [comment]
Thanks for the clarification :bow:
